bucket = "terraform-backend-alam"
validation_hour = "1234"
cert_request_pem = "../../secrets/CSR/example.maifuj.com/csr.csr"
ca_cert_pem = "../../secrets/cert/root-ca/root-ca.cert"
ca_private_key_pem = "../../secrets/keys/RSA/root-ca"
